### ISSUE TITLE
设置频道属性发生异常

### ISSUE THREAD

**Issue by ahjszll** [AgoraIO-Community/Agora-Unity-RTM-SDK#15]
`AGORA_API int setChannelAttributes(void *rtmInstance, const char* channelId, long long attributes[], const int numberOfAttributes, bool enableNotificationToChannelMembers, long long requestId)
{
	if (numberOfAttributes <= 0)
		return -1;

    agora::rtm::ChannelAttributeOptions channelAttributeOptions;
    channelAttributeOptions.enableNotificationToChannelMembers = enableNotificationToChannelMembers;

	std::vector<const agora::rtm::IRtmChannelAttribute *> test;
	test.resize(numberOfAttributes);

	for(int i = 0; i < numberOfAttributes; i++) {
	    test.push_back(reinterpret_cast<agora::rtm::IRtmChannelAttribute *>(attributes[i]));
	}

    return RTM_SERVICE_INSTANCE->setChannelAttributes(channelId, &test[0], numberOfAttributes, channelAttributeOptions, requestId);
}`
这里设置频道属性，test.resize(numberOfAttributes) 会新增一个null对象，执行RTM_SERVICE_INSTANCE->setChannelAttributes，发生异常

![QQ截图20210107154620](https://user-images.githubusercontent.com/3364600/103865688-86009600-50ff-11eb-9a69-602d25ce35fb.png)

**Comment by zhangtao1104** [comment]
已经修复，可以更新代码再试下。
