### ISSUE TITLE
RTM & RTC at the same time?

### ISSUE THREAD

**Issue by morettyCat** [AgoraIO-Community/Agora-Unity-RTM-SDK#19]
Hi there, every time I try to initialize RTM & RTC both at the same time (video call and chat) the app on iOS just crash.

The fastest way to reproduce is to get RTC demo, and paste on the HelloVideo scene the components that comes in the demo with RTM in this package (canvas and manager). It works perfectly on Android & Editor, but on iOS it definetly crash with not too much info.

Can anyone tall me if it's possible to get both Agora frameworks work together??

<img width="886" alt="Captura de Pantalla 2021-01-29 a les 15 03 27" src="https://user-images.githubusercontent.com/44590948/106289174-3bc78c00-6249-11eb-99e4-29a5fd8291d4.png">

**Comment by morettyCat** [comment]
The error whoen on the previous image is thrown when you click "Join" button and it initializes the RTM (and we already have the RTC initialized without problems)

**Comment by zhangtao1104** [comment]
Ok, I will confirm this issue. Then give you a feedback.

**Comment by zhangtao1104** [comment]
I had confirm this problem, because the rtm sdk is static library, the rtc sdk contain the rtm sdk, so it will conflict if you use both rtc sdk and rtm sdk. We will fix this problem in next rtm sdk version.

**Comment by morettyCat** [comment]
Meanwhile, do you think is it possible to use both? I mean, if RTC actually contains the RTM, will it work if I only attach RTC?

**Comment by zhangtao1104** [comment]
You can use both of them If we provide a RTM dynamic framework.

Yes, RTC contains RTM, but RTC don't expose RTM api yet.

**Comment by morettyCat** [comment]
And do you know if there is any older version or something we can use now?

We are developing an app that should be releasing soon and this integration is our only stopper right now : /

Is there any help that can come from my team to achieve this? Maybe we can branch this to achive dynamic framework instead of static and share it to any other interested people. Any orientatiom will be ultra appreciated!!

**Comment by zhangtao1104** [comment]
I commuicate with my team about this issue, if there is any result, i will tell you.

**Comment by morettyCat** [comment]
I don't wanna be exigent, but how much time do you think will it take to get it? We choose Agora because of the easy integration, but if this is not going to work in a short time we will probably choose other solutions. Can we get an estimate time even if it's not exact?

**Comment by zhangtao1104** [comment]
Can you show me the api that you call  of  rtc and rtm?  Maybe we have some easy way to solve this problem.

**Comment by zhangtao1104** [comment]
I had fix the problem, You can clone the project and build the sdk yourself.

1: You just need to run the scripts in 
Agora-Unity-RTM-SDK/unity_rtm_sdk/Projects/Android/build.sh
                                                                                 /IOS/agoraRTMCWrapper/build.sh
                                                                                /macOS/agoraRTMCWrapper/build.sh
Then you just need to replace the new library.

2: You also need to replace  all of the C# api interface scripts in Agora-Unity-RTM-SDK/unity_rtm_sdk/Projects/Rtm-Scripts/

Then I think you can fix your problem.

Please have a try.

**Comment by morettyCat** [comment]
Nice!! I’ll try tomorrow with my team and let you know as soon as possible!

thanks in advance!!! : )

**Comment by morettyCat** [comment]
It just works like a charm!!! I own you a beer @zhangtao1104 !!!!
