### ISSUE TITLE
你好。 我对Unity-RTM-Demo有疑问。

### ISSUE THREAD

**Issue by dh7300** [AgoraIO-Community/Agora-Unity-RTM-SDK#20]
收到演示后，导入SDK并输入AppID和令牌后，输入用户名并单击LOGIN。
“客户端登录失败！ID = 0错误代码= LOGIN_ERR_INVALID_APP_ID”
“连接状态已更改ID：0状态：CONNECTION_STATE_DISCONNECTED原因：CONNECTION_CHANGE_REASON_LOGIN_FAILURE”
这些错误显示在debug.log中。 我需要帮助。

**Comment by zhangtao1104** [comment]
你需要根据 Unity-RTM-Demo 的 README 的流程去做，报这个错误的原因应该是你没有 注册 appId，Demo 里需要正确的注册过的 appId 才可以正常运行。

**Comment by dh7300** [comment]
<img width="527" alt="ap" src="https://user-images.githubusercontent.com/69621922/108317587-d93b2d80-7201-11eb-9909-a397c31afb2c.png">

I did read the README.
  Put the APPID at the top of the image in the APPID
I put the APP certificate at the bottom of the image in TOKEN.
Still, when I press the login button after writing the username, it says that it failed. Am I wrong?

**Comment by zhangtao1104** [comment]
You can use Testing mode with no certificate and then you just need to copy the appId.

At last you just need to paste the appId into the property which is located at "MainScene/ChatManager/AppId".

Then you can run the demo.

**Comment by ROBYER1** [comment]
If you did what I did, which was assume the RTM SDK was a part of the Unity Agora SDK from the Asset store, you are wrong as I was. Import this release package into your project and RTM examples from this repo will work as long as you use a valid AppId

https://github.com/AgoraIO-Community/Agora-Unity-RTM-SDK/releases/tag/v1.4.2.301.2
