### ISSUE TITLE
.Joint() channel crash if Agora RTC is in the Unity projet

### ISSUE THREAD

**Issue by N7Nico** [AgoraIO-Community/Agora-Unity-RTM-SDK#22]
Hello ! ^^
Since your last update, there is no more conflict between RTC and RTM at import time.
But now, if in a project, you import both SDK and start the demo RTM Scene on iOS: the app crash on the .Joint() call.

If I delete the Agora RTC SDK and compile it again on iOS, it starts working again.

Is there any solution ? Am I missing something ?

Best regards,
Nicolas

**Comment by zhangtao1104** [comment]
Hello, you can try to solve this problem according to this issue: 

https://github.com/AgoraIO-Community/Agora-Unity-RTM-SDK/issues/19

**Comment by N7Nico** [comment]
Hello,
Oh I missed it when browsing old issues.
I will test it as soon as I can and keep you informed.

I will close the issue.
Thank you for your guidance ! :)
