### ISSUE TITLE
Exception: Field currentActivity or type signature  not found 

### ISSUE THREAD

**Issue by SeadnaS** [AgoraIO-Community/Agora-Unity-RTM-SDK#3]
On line 537 in RtmWrapperAndroid.cs I get the following exception when I try to run as Android platform in editor:

Exception: Field currentActivity or type signature  not found
UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName, System.String signature, System.Boolean isStatic) (at C:/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:1445)
UnityEngine.AndroidJNIHelper.GetFieldID (System.IntPtr javaClass, System.String fieldName, System.String signature, System.Boolean isStatic) (at C:/buildslave/unity/build/Modules/AndroidJNI/AndroidJNI.bindings.cs:79)
UnityEngine._AndroidJNIHelper.GetFieldID[ReturnType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at C:/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:1358)
UnityEngine.AndroidJNIHelper.GetFieldID[FieldType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at C:/buildslave/unity/build/Modules/AndroidJNI/AndroidJNI.bindings.cs:172)
UnityEngine.AndroidJavaObject._GetStatic[FieldType] (System.String fieldName) (at C:/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:663)
UnityEngine.AndroidJavaObject.GetStatic[FieldType] (System.String fieldName) (at C:/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:274)
io.agora.rtm.RtmWrapperAndroid.CreateRtmServiceAndLogin (System.String appId, System.String token, System.String username) (at Assets/AgoraEngineRTM/Scripts/AgoraRtmSDK/RtmWrapperAndroid.cs:537)
io.agora.rtm.IRtmWrapper.Login (System.String appId, System.String token, System.String username) (at Assets/AgoraEngineRTM/Scripts/AgoraRtmSDK/RtmWrapper.cs:119)
GCRoom.loadEngine (System.String appId) (at Assets/AgoraEngine/GroupCall/GCRoom.cs:47)
GCHome.onJoinButtonClicked (System.String text) (at Assets/AgoraEngine/GroupCall/GCHome.cs:85)
GCHome.hostGroupCallButtonClicked () (at Assets/AgoraEngine/GroupCall/GCHome.cs:76)
UnityEngine.Events.InvokableCall.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent/UnityEvent.cs:166)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent/UnityEvent/UnityEvent_0.cs:58)
UnityEngine.UI.Button.Press () (at C:/Program Files/Unity/Hub/Editor/2019.2.19f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:68)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/Program Files/Unity/Hub/Editor/2019.2.19f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/UI/Core/Button.cs:110)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/Program Files/Unity/Hub/Editor/2019.2.19f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at C:/Program Files/Unity/Hub/Editor/2019.2.19f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update() (at C:/Program Files/Unity/Hub/Editor/2019.2.19f1/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:377)

**Comment by jakep84** [comment]
Hi Seadna, 
Thanks for finding this hidden feature. Seems we are still allowing Android-specific code to be called even though you are running in the editor. Sorry about that. The fix is done by adding ` && !UNITY_EDITOR ` to line 18 of the RtmWrapper.cs script, where we are calling the desired wrapper based on what platform we are running. I'll add the update now 👍

**Comment by SeadnaS** [comment]
Thanks Jake that worked a treat.
