### ISSUE TITLE
iOS:  Class AgoraReachability is implemented in both [path] and [path]. One of the two will be used. Which one is undefined.

### ISSUE THREAD

**Issue by ipsodev** [AgoraIO-Community/Agora-Unity-RTM-SDK#35]
Hi.
I have built a test app that uses both the Agora-Unity-RTM-SDK as well as the Agora Unity Video SDK . App works fine on Windows + Android.

RtmClient: 1.4.2.301
Agora SDK: 3.3.1
Unity: 2021..1.5f

The crash below happens on startup in XCODE (Unity splashscreen).

objc[1771]: Class AgoraReachability is implemented in both /private/var/containers/Bundle/Application/C6D25DB7-9279-4919-8632-235DDB9D7DB7/YpsoPumpRemoteTraining.app/Frameworks/AgoraRtcKit.framework/AgoraRtcKit (0x10a69f190) and /private/var/containers/Bundle/Application/C6D25DB7-9279-4919-8632-235DDB9D7DB7/YpsoPumpRemoteTraining.app/Frameworks/UnityFramework.framework/UnityFramework (0x106c609e8). One of the two will be used. Which one is undefined.

How do I fix this error?

Many thanks.

**Comment by plutoless** [comment]
i think this is just a warning, it's usually not causing any problems. are there any crash dumps?

**Comment by ipsodev** [comment]
Hi. 
I refactored my code. Crash seems to have disappeared. Not sure what I did to fix it. All is working now. 
You are correct. The warning is still logged but doesn't seem to be causing the issue.
Thank you so much for looking at the problem.
