### ISSUE TITLE
RTM login issue

### ISSUE THREAD

**Issue by RajaChandiran** [AgoraIO-Community/Agora-Unity-RTM-SDK#36]
when two user join in the same channel, there is a quiet  delay in the chat response and also if another user joins the channel then the login failed error is showing.

**Comment by zhangtao1104** [comment]
Is this issue always appear in this scene.

**Comment by RajaChandiran** [comment]
> Is this issue always appear in this scene.

yes

**Comment by zhangtao1104** [comment]
Can you help to provide some error log? I can reproduce this issue according to your information.

**Comment by icywind** [comment]
not reproducible
