### ISSUE TITLE
iOS Framework Signing Error

### ISSUE THREAD

**Issue by ARUtility** [AgoraIO-Community/Agora-Unity-RTM-SDK#4]
The RTM plugin has worked great on Android. However, when deploying to iOS we run into issues. I have followed the ReadME instructions and changed the RTMIOS framework to "Embed and Sign". On first try the app crashed immediately once it finished building with the error "not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed." So I went back to the "unityFramework" target and signed with our developer certificate. Knowing that this probably wasn't going to work. However, it did launch when connected to the debugger. Once the debugger is disconnected the app can no longer be launched and it crashes immediately on launch every time. From all of the research we have done, this appears to be a signing issue with the framework. As soon as we remove the RTM scripts and plugin the app works perfectly fine. So we have narrowed it down to the RTM plugin and something to do with the signing of that linked framework.

Any thoughts on how to remedy this? We've exhausted all of our resources trying to find an answer. Thanks in advance for any help you can offer.

**Comment by SeadnaS** [comment]
Is it possible that you accidentally chose "embed without signing" on the RTMIOS framework?

**Comment by ARUtility** [comment]
> Is it possible that you accidentally chose "embed without signing" on the RTMIOS framework?

We made sure it was set as "embed and sign" as per the Readme instructions.

**Comment by icywind** [comment]
If you still have issues, please see my reply to https://github.com/AgoraIO-Community/Unity-RTM/issues/5
