### ISSUE TITLE
EntryPointNotFound error when initializing RTM in editor

### ISSUE THREAD

**Issue by SeadnaS** [AgoraIO-Community/Agora-Unity-RTM-SDK#5]
We have successfully implemented RTM in unity on Android however we are having issues with iOS now where RTM will not initialize. On line 201 of RtmWrapperIOS.cs we get an exception:

**EntryPointNotFoundException: getSDKVersion**

Any idea how to overcome this issue?

**Comment by SeadnaS** [comment]
Does anybody have any ideas on how to solve this. This is still a major blocker for us as our app is severely limited on iOS without the use of RTM.

**Comment by icywind** [comment]
Sorry the original author has left Agora.  Here is what I found working in my XCode project:
![rtm2018-sign](https://user-images.githubusercontent.com/1261195/90598897-c68b6180-e1a8-11ea-841c-12d06cf635d2.png)
![rtm2019-sign](https://user-images.githubusercontent.com/1261195/90599047-05211c00-e1a9-11ea-9b2b-ac8114101a0d.png)
