### ISSUE TITLE
Still having issues with iOS

### ISSUE THREAD

**Issue by SeadnaS** [AgoraIO-Community/Agora-Unity-RTM-SDK#7]
As a follow up to issue #5 i am still having issues with this lib in iOS. I made sure to embed the  RTMiOS framework as suggested but I now get a SIGABRT error with message "terminating with uncaught exception of type il2cppexceptionwrapper". In xcode it highlights line 40 of main.mm "UIApplicationMain(argc, argv, nil, [NSString stringWithUTF8String: AppControllerClassName]);"

**Comment by icywind** [comment]
Hmmm, not sure what you have in your environment.  I put up [a video recording](https://bit.ly/3aWvPEa) on what I did.  There shouldn't be any crashing and the demo should print the RTM version number when it launched.  ("1.2.2").

**Comment by icywind** [comment]
Hi @SeadnaS, is this still an issue for you?

**Comment by SeadnaS** [comment]
Yes we are still having the same issue. I checked that our solution was set
up similar to the video you sent. Do you have a working unity example that
we can look at?

**Comment by SeadnaS** [comment]
I have revisited this issue. I downloaded the latest version of RTM for Unity and updated the code to incorporate it. Unfortunately I keep getting these errors when building the XCode project:

Undefined symbol: _getRtmSdkVersion

and

Undefined symbol: _createRtmService

Ld /Users/seadnasmallwood/Library/Developer/Xcode/DerivedData/Unity-iPhone-entaiobhvuyfaxbknudebvgsekvy/Build/Products/ReleaseForRunning-iphoneos/Workflow.app/Workflow normal arm64 (in target 'Unity-iPhone' from project 'Unity-iPhone')
    cd /Users/seadnasmallwood/Documents/2-15-1
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-ios9.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.5.sdk -L/Users/seadnasmallwood/Library/Developer/Xcode/DerivedData/Unity-iPhone-entaiobhvuyfaxbknudebvgsekvy/Build/Products/ReleaseForRunning-iphoneos -L/Users/seadnasmallwood/Documents/2-15-1 -L/Users/seadnasmallwood/Documents/2-15-1/Libraries -L/Users/seadnasmallwood/Documents/2-15-1/Libraries/AgoraEngine/Plugins/iOS -L/Users/seadnasmallwood/Documents/2-15-1/Libraries/NatCorder/Plugins/iOS -L/Users/seadnasmallwood/Documents/2-15-1/Libraries/NatSuite/Plugins/iOS -L/Users/seadnasmallwood/Documents/2-15-1/Libraries/RTM-Engine/Plugins/Release-iphoneos -L/Users/seadnasmallwood/Documents/2-15-1/Libraries/Plugins/SqlCipher4Unity3D/Plugins/iOS -F/Users/seadnasmallwood/Library/Developer/Xcode/DerivedData/Unity-iPhone-entaiobhvuyfaxbknudebvgsekvy/Build/Products/ReleaseForRunning-iphoneos -F/Users/seadnasmallwood/Documents/2-15-1/Frameworks/AgoraEngine/Plugins/iOS -F/Users/seadnasmallwood/Documents/2-15-1/Frameworks/WebRtcVideoChat/Plugins/ios/universal -filelist /Users/seadnasmallwood/Library/Developer/Xcode/DerivedData/Unity-iPhone-entaiobhvuyfaxbknudebvgsekvy/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/Workflow.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -map -Xlinker /Users/seadnasmallwood/Library/Developer/Xcode/DerivedData/Unity-iPhone-entaiobhvuyfaxbknudebvgsekvy/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Workflow-LinkMap-normal-arm64.txt -dead_strip -Xlinker -object_path_lto -Xlinker /Users/seadnasmallwood/Library/Developer/Xcode/DerivedData/Unity-iPhone-entaiobhvuyfaxbknudebvgsekvy/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/Workflow_lto.o -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -weak_framework CoreMotion -weak-lSystem -framework Security -framework MediaToolbox -liPhone-lib -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework AVKit -framework CFNetwork -framework CoreGraphics -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp -lcrypto -framework AgoraRtcEngineKit -framework AgoraRtcCryptoLoader -lNatCorder_old -framework AgoraRtcKit -lNatCorder -lagoraRTMCWrapper -lsqlcipher -lagoraSdkCWrapper -lNatCamRenderPipeline -framework webrtccsharpwrap -framework CoreFoundation -framework GLKit -weak_framework Accelerate -weak_framework CoreTelephony -weak_framework CoreML -weak_framework VideoToolbox -weak-liPhone-lib -weak-lresolv -framework WebKit -weak_framework Metal -Xlinker -dependency_info -Xlinker /Users/seadnasmallwood/Library/Developer/Xcode/DerivedData/Unity-iPhone-entaiobhvuyfaxbknudebvgsekvy/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/Workflow_dependency_info.dat -o /Users/seadnasmallwood/Library/Developer/Xcode/DerivedData/Unity-iPhone-entaiobhvuyfaxbknudebvgsekvy/Build/Products/ReleaseForRunning-iphoneos/Workflow.app/Workflow

Undefined symbols for architecture arm64:
  "_getRtmSdkVersion", referenced from:
      __getRtmSdkVersion_ in libagoraRTMCWrapper.a(i_rtm_service.o)
     (maybe you meant: _IRtmApiNative__getRtmSdkVersion__m9FF410029CE138770CB8E07756B8F717373C0AA8, __getRtmSdkVersion_ )
  "_createRtmService", referenced from:
      _createRtmService_ in libagoraRTMCWrapper.a(i_rtm_service.o)
     (maybe you meant: _IRtmApiNative_createRtmService__m9CACB07BBBEE5BABC8EA8667268C5233790D8661, _createRtmService_ )
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
