### ISSUE TITLE
CallInvitation

### ISSUE THREAD

**Issue by bastidererste** [AgoraIO-Community/Agora-Unity-RTM-SDK#8]
CallInvitation seams to be implemented only partially. Any plan on implementing this? thx

**Comment by zhangtao1104** [comment]
we will support all callinvitation function next version, it maybe publish in December.

**Comment by bastidererste** [comment]
Awesome! And this will be implemented for all platforms? MacOS, Win, iOS?

**Comment by zhangtao1104** [comment]
Yes, we will support Android, iOS, Windows, macOS.

**Comment by icywind** [comment]
The new SDK has been released. Please check the release page for the package.
